spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/nobrain
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  jwt:
    secret: govlepel@$&

app:
  domain: /api
