### COOL SMS ###
COOLSMS:
  API_KEY: ENC(YILdY+2oVQp+YhMMnCIZi8WuP90aCuEJ6WMcBFO8B7Q=)
  API_SECRET_KEY: ENC(pLYaAL3kckEliQ+mzkg4b/jMmW0YpJ+jJmlO/Zs4SwXGfZOk2GPXZmlX0z77zrms)
  PHONE_NUMBER: ENC(GNWBVJnTUhD05aNzoh+baQFZemsskHmi)