server:
  port: 8080

spring:
  profiles:
    default: prod

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

app:
  domain: /api

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDes
    pool-size: 1
    output-type: base64
    iterations: 1000