server:
  port: 8080

spring:
  profiles:
    include:
      - prod
      - API-KEY
      - aws
      - oauth

  jwt:
    secret: ENC(zoV04jn/ttqdTIsRL/QTriKYAHCsjsoihsm5KjXfm2C+Z0TsX8ZHdWHmoizPf2rU)in

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(y9kWKMRAy5c2RwJ68FrK4MBIP82AMK8RShFwxm5hp/Q=)
    password: ENC(j0qRQzDRgoFJEzBz4bT8uXdIvLlmYK12TVEugCbmjrI=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

app:
  domain: /api

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDes
    pool-size: 1
    output-type: base64
    iterations: 1000