global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: 'nobrain-monitor'

scrape_configs:
  - job_name: 'nobrain-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8089']